## PTDF OPF notebook - import gen excel and load excel, and network data.

In [1]:
import pandas as pd

In [ ]:
Lines = pd.read_csv('../data/Inputs_prepared/Lines.csv')
Links = pd.read_csv('../data/Inputs_prepared/Links.csv')
Transformers = pd.read_csv('../data/Inputs_prepared/Transformers.csv')

,LinkID,link_name,bus0,bus1,voltage,capacity,x,length,under_construction
0,1,relation/10377412-320-DC,way/753113423,way/636630368-400,320,1000,0.01,230137.18,f
1,2,relation/13295785-515-DC,relation/12832053,way/642490160,515,1400,0.01,723362.06,f
2,3,relation/14126301-450-DC,way/109189896,way/920127890,450,1000,0.01,253393.42,f
3,4,relation/15772117-320-DC,way/775577829-400,way/775577827,320,1000,0.01,51576.89,f
4,5,relation/15775538-600-DC,way/297840585,way/375626500-400,600,2250,0.01,397643.50,f
5,6,relation/15777152-320-DC,way/1262971878,way/975637991,320,600,0.01,282108.95,f
6,7,relation/15781671-525-DC,way/1078532568-400,way/1101832649,525,1400,0.01,740934.57,f
7,8,relation/2127794-270-DC,way/23281217-400,way/1271288346,270,2000,0.01,69019.25,f
8,9,relation/6914309-500-DC,way/137050527-275,way/148382435,500,500,0.01,61383.39,f
9,10,relation/8099179-320-DC,way/1262971878,way/568527671,320,1200,0.01,161431.49,f
10,11,relation/8184641-400-DC,way/536905500-400,way/260836695,400,500,0.01,254728.97,f
11,12,relation/8185487-400-DC,relation/10695345-400,way/500788534,400,1000,0.01,139235.71,f

In [29]:
Lines = Lines.rename(columns={
    'LineID': 'AssetID'
})

Links = Links.rename(columns={
    'LinkID': 'AssetID'
})

Transformers = Transformers.rename(columns={
    'TransformerID': 'AssetID'
})

Lines["type"] = "Line"
Links["type"] = "Link"
Transformers["type"] = "Transformer"

network = pd.concat([Lines, Links, Transformers], ignore_index=True)

network['AssetID'] = range(1, len(network)+1)

network

,AssetID,bus0,bus1,voltage,capacity,r,x,b,length,under_construction,type,link_name,voltage_bus0,voltage_bus1,s_nom
0,1,way/1307462736-275,way/86071326-275,275.0,921.668,2.200334,14.577213,0.000228,55008.35,f,Line,NaN,NaN,NaN,NaN
1,2,relation/7881280-400,relation/13110369-400,400.0,3574.953,0.420393,3.447219,0.000243,28026.17,f,Line,NaN,NaN,NaN,NaN
2,3,way/101077623-275,GB41-275,275.0,1843.335,0.046871,0.310518,0.000019,2343.53,f,Line,NaN,NaN,NaN,NaN
3,4,way/95279334-400,way/103915328-400,400.0,3574.953,0.425859,3.492045,0.000246,28390.61,f,Line,NaN,NaN,NaN,NaN
4,5,way/111528318-220,GB8-220,220.0,1474.668,1.584632,7.949573,0.000933,79231.62,f,Line,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,736,way/536905500-400,way/536905500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Transformer,NaN,400.0,400.0,NaN
736,737,way/568527671,way/166703766-275,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Transformer,NaN,320.0,275.0,NaN
737,738,way/636630368-400,way/636630368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Transformer,NaN,400.0,320.0,NaN
738,739,way/642490160,way/310502642-275,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Transformer,NaN,515.0,275.0,NaN
739,740,way/775577829-400,way/775577829,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Transformer,NaN,400.0,320.0,NaN

In [ ]:
# import networkx as nx

# # Build an undirected graph
# G = nx.Graph()

# # Add all edges from your DataFrame
# for _, row in network.iterrows():
#     G.add_edge(row["bus0"], row["bus1"])

# # Number of connected components
# n_components = nx.number_connected_components(G)

# print("Number of connected components:", n_components)

# if n_components == 1:
#     print("✅ The network is fully connected.")
# else:
#     print("❌ The network is NOT fully connected.")
#     print("Connected components:")
#     for comp in nx.connected_components(G):
#         print(" - component with", len(comp), "buses")

Number of connected components: 1
✅ The network is fully connected.

In [36]:
network = network.rename(columns={
    'capacity': 'Capacity',
    'bus0': 'Bus0',
    'bus1': 'Bus1',
    'voltage': 'Voltage',
    'type': 'Type',
    })

network = network[['AssetID', 'Bus0', 'Bus1', 'Capacity', 'x', 'Voltage','Type']]

network['Capacity'] = network['Capacity'].fillna(network['Capacity'].mean())
network['x'] = network['x'].fillna(0.01)
network['Voltage'] = network['Voltage'].fillna(400)
network

,AssetID,Bus0,Bus1,Capacity,x,Voltage,Type
0,1,way/1307462736-275,way/86071326-275,921.668000,14.577213,275.0,Line
1,2,relation/7881280-400,relation/13110369-400,3574.953000,3.447219,400.0,Line
2,3,way/101077623-275,GB41-275,1843.335000,0.310518,275.0,Line
3,4,way/95279334-400,way/103915328-400,3574.953000,3.492045,400.0,Line
4,5,way/111528318-220,GB8-220,1474.668000,7.949573,220.0,Line
...,...,...,...,...,...,...,...
735,736,way/536905500-400,way/536905500,2161.388097,0.010000,400.0,Transformer
736,737,way/568527671,way/166703766-275,2161.388097,0.010000,400.0,Transformer
737,738,way/636630368-400,way/636630368,2161.388097,0.010000,400.0,Transformer
738,739,way/642490160,way/310502642-275,2161.388097,0.010000,400.0,Transformer
739,740,way/775577829-400,way/775577829,2161.388097,0.010000,400.0,Transformer

## Save

In [38]:
units = pd.read_excel("Cost_and_Carbon.xlsx", sheet_name="Units_with_regions")
load_profile = pd.read_excel("Load.xlsx", sheet_name='2024-03-31')
load_weights = pd.read_excel("Load.xlsx", sheet_name='load_weights')

with pd.ExcelWriter("PTDF_OPF.xlsx") as writer:
    network.to_excel(writer, sheet_name="network", index=False)
    units.to_excel(writer, sheet_name="units", index=False)
    load_profile.to_excel(writer, sheet_name="load_profile", index=False)
    load_weights.to_excel(writer, sheet_name="load_weights", index=False)

1. network figure: line width -> capacity
2. interconnector capacity -> network